<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCnCV0t9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCnCV0t9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCnCV0t9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCnCV0t9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCnCV0t9\App_KernelDevDebugContainer([
    'container.build_hash' => 'CnCV0t9',
    'container.build_id' => '191f32e7',
    'container.build_time' => 1599818754,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCnCV0t9');
